/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as GameRouteImport } from './routes/game'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameCategoryIdRouteImport } from './routes/game.$categoryId'
import { Route as AdminTutorialsRouteImport } from './routes/admin/tutorials'
import { Route as AdminDocsRouteImport } from './routes/admin/docs'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTranslationsRouteImport } from './routes/admin/translations'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminClassesRouteImport } from './routes/admin/classes'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedTutorialsRouteImport } from './routes/_authenticated/tutorials'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQuizzesRouteImport } from './routes/_authenticated/quizzes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCategoryIdRoute = GameCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => GameRoute,
} as any)
const AdminTutorialsRoute = AdminTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocsRoute = AdminDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTutorialsRoute = AuthenticatedTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizzesRoute = AuthenticatedQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/game': typeof GameRouteWithChildren
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/quizzes': typeof AuthenticatedQuizzesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/tutorials': typeof AuthenticatedTutorialsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/game/$categoryId': typeof GameCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/game': typeof GameRouteWithChildren
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/quizzes': typeof AuthenticatedQuizzesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/tutorials': typeof AuthenticatedTutorialsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/game/$categoryId': typeof GameCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/game': typeof GameRouteWithChildren
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/quizzes': typeof AuthenticatedQuizzesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/tutorials': typeof AuthenticatedTutorialsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/game/$categoryId': typeof GameCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/game'
    | '/guest'
    | '/login'
    | '/reset-password'
    | '/analytics'
    | '/classes'
    | '/dashboard'
    | '/docs'
    | '/quizzes'
    | '/settings'
    | '/students'
    | '/tutorials'
    | '/admin/classes'
    | '/admin/content'
    | '/admin/docs'
    | '/admin/tutorials'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/game/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/game'
    | '/guest'
    | '/login'
    | '/reset-password'
    | '/analytics'
    | '/classes'
    | '/dashboard'
    | '/docs'
    | '/quizzes'
    | '/settings'
    | '/students'
    | '/tutorials'
    | '/admin/classes'
    | '/admin/content'
    | '/admin/docs'
    | '/admin/tutorials'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/game/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/game'
    | '/guest'
    | '/login'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/classes'
    | '/_authenticated/dashboard'
    | '/_authenticated/docs'
    | '/_authenticated/quizzes'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/tutorials'
    | '/admin/classes'
    | '/admin/content'
    | '/admin/docs'
    | '/admin/tutorials'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/game/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  GameRoute: typeof GameRouteWithChildren
  GuestRoute: typeof GuestRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/docs': {
      id: '/admin/docs'
      path: '/docs'
      fullPath: '/admin/docs'
      preLoaderRoute: typeof AdminDocsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$categoryId': {
      id: '/game/$categoryId'
      path: '/$categoryId'
      fullPath: '/game/$categoryId'
      preLoaderRoute: typeof GameCategoryIdRouteImport
      parentRoute: typeof GameRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tutorials': {
      id: '/admin/tutorials'
      path: '/tutorials'
      fullPath: '/admin/tutorials'
      preLoaderRoute: typeof AdminTutorialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/tutorials': {
      id: '/_authenticated/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof AuthenticatedTutorialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quizzes': {
      id: '/_authenticated/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AuthenticatedQuizzesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedQuizzesRoute: typeof AuthenticatedQuizzesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedTutorialsRoute: typeof AuthenticatedTutorialsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedQuizzesRoute: AuthenticatedQuizzesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedTutorialsRoute: AuthenticatedTutorialsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminClassesRoute: typeof AdminClassesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDocsRoute: typeof AdminDocsRoute
  AdminTutorialsRoute: typeof AdminTutorialsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClassesRoute: AdminClassesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDocsRoute: AdminDocsRoute,
  AdminTutorialsRoute: AdminTutorialsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GameRouteChildren {
  GameCategoryIdRoute: typeof GameCategoryIdRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameCategoryIdRoute: GameCategoryIdRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  GameRoute: GameRouteWithChildren,
  GuestRoute: GuestRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
